# Project Title: IEEE-CIS Fraud Detection
# Project Goal: Applying EDA techniques and machine learning models to help business reduce credit card fraud
# Author:
## Name: Chisom Micheal Eriobu
## Email: Chisomichealeriobu428@gmail.com

In [1]:
# import libaries for EDA
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
# load data
train_transaction=pd.read_csv("train_transaction.csv")
train_identity=pd.read_csv("train_identity.csv")
test_identity=pd.read_csv('test_identity.csv')
test_transaction=pd.read_csv('test_transaction.csv')

In [3]:
# preview train_identity data
train_identity.tail(50)

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
144183,3577240,-10.0,800032.0,NaN,NaN,13.0,-9.0,NaN,NaN,NaN,...,chrome 57.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,LG-E975
144184,3577244,-25.0,484895.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
144185,3577251,-5.0,121964.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,ie 11.0 for desktop,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Trident/7.0
144186,3577260,-10.0,219282.0,0.0,0.0,15.0,-9.0,NaN,NaN,0.0,...,chrome 57.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,LG-E975
144187,3577265,-20.0,430910.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,safari 11.0,NaN,NaN,NaN,F,F,F,F,desktop,NaN
144188,3577278,-10.0,121866.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 49.0,NaN,NaN,NaN,F,T,T,F,desktop,NaN
144189,3577282,-10.0,173248.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,ie 11.0 for desktop,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Trident/7.0
144190,3577287,-5.0,456818.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,RCT6513W87 Build/MRA58K
144191,3577296,-5.0,191315.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 64.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J500M Build/MMB29M
144192,3577298,-5.0,86977.0,0.0,0.0,2.0,-2.0,NaN,NaN,0.0,...,chrome 67.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144193,3577299,-100.0,310155.0,NaN,NaN,22.0,-26.0,NaN,NaN,NaN,...,mobile safari 11.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
144194,3577302,-5.0,42161.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0,24.0,1600x900,match_status:2,T,F,T,T,desktop,Windows
144195,3577318,-10.0,258188.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,ie 11.0 for desktop,24.0,1920x1080,match_status:2,T,F,T,T,desktop,Trident/7.0
144196,3577325,-5.0,85234.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 66.0,24.0,1920x1080,match_status:2,T,F,T,F,desktop,Windows
144197,3577329,-5.0,16963.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 65.0,24.0,1920x1080,match_status:2,T,F,T,F,desktop,MacOS
144198,3577338,-5.0,198598.0,NaN,NaN,5.0,0.0,NaN,NaN,0.0,...,safari 11.0,24.0,1440x900,match_status:2,T,F,F,T,desktop,MacOS
144199,3577343,-5.0,57445.0,NaN,NaN,4.0,0.0,NaN,NaN,0.0,...,safari 11.0,24.0,1440x900,match_status:2,T,F,F,T,desktop,MacOS
144200,3577344,-5.0,22868.0,0.0,0.0,4.0,0.0,NaN,NaN,0.0,...,safari 11.0,24.0,1440x900,match_status:2,T,F,F,T,desktop,MacOS
144201,3577347,-5.0,132327.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 65.0,24.0,1600x1200,match_status:2,T,F,T,T,desktop,Windows
144202,3577351,-20.0,190267.0,NaN,NaN,-5.0,-20.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G610F Build/NRD90M
144203,3577354,-25.0,229668.0,0.0,0.0,-5.0,-20.0,NaN,NaN,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G610F Build/NRD90M
144204,3577364,-5.0,183132.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,samsung browser 6.4,NaN,NaN,NaN,F,F,T,F,mobile,SAMSUNG SM-J700M Build/MMB29K
144205,3577365,-10.0,112037.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,firefox 60.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144206,3577368,-5.0,214747.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,2208x1242,match_status:1,T,F,F,T,mobile,iOS Device
144207,3577384,-20.0,50886.0,0.0,0.0,13.0,-34.0,39.0,-100.0,0.0,...,mobile safari 11.0,32.0,2436x1125,match_status:1,T,F,T,T,mobile,iOS Device
144208,3577397,-5.0,313942.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144209,3577410,-5.0,211823.0,NaN,NaN,6.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:2,T,F,F,T,mobile,iOS Device
144210,3577418,-45.0,118160.0,NaN,NaN,10.0,-9.0,NaN,NaN,NaN,...,chrome 66.0 for android,24.0,1920x1080,match_status:2,T,F,T,F,mobile,SM-G930T Build/NRD90M
144211,3577437,-5.0,72127.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 66.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144212,3577440,-5.0,76483.0,NaN,NaN,2.0,0.0,NaN,NaN,3.0,...,chrome 66.0,24.0,2560x1600,match_status:2,T,F,T,F,desktop,MacOS
144213,3577442,-20.0,89189.0,NaN,NaN,NaN,NaN,14.0,-24.0,0.0,...,ie 11.0 for desktop,24.0,1024x768,NaN,T,F,F,T,desktop,Trident/7.0
144214,3577445,-5.0,107251.0,0.0,0.0,6.0,0.0,NaN,NaN,0.0,...,safari 11.0,24.0,1440x900,match_status:1,T,F,F,T,desktop,MacOS
144215,3577447,-5.0,43053.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0,24.0,1280x1024,match_status:2,T,F,T,T,desktop,Windows
144216,3577451,-25.0,130543.0,NaN,NaN,-2.0,-33.0,12.0,-51.0,NaN,...,google,32.0,2001x1125,match_status:2,T,F,T,F,mobile,iOS Device
144217,3577465,-5.0,111397.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,safari 11.0,24.0,2560x1440,match_status:2,T,F,F,F,desktop,MacOS
144218,3577469,-10.0,62155.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 65.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144219,3577472,-5.0,345613.0,NaN,NaN,-11.0,-30.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G930F Build/NRD90M
144220,3577476,-10.0,81665.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 65.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144221,3577478,-5.0,109718.0,NaN,NaN,14.0,-20.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144222,3577486,-5.0,599833.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 67.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G950F Build/R16NW
144223,3577495,-5.0,56061.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0,24.0,1280x1024,match_status:2,T,F,T,T,desktop,Windows
144224,3577499,-5.0,89753.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,firefox 60.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144225,3577501,-5.0,59763.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,firefox 60.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
144226,3577506,0.0,82599.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,ie 11.0 for desktop,24.0,1600x900,match_status:2,T,T,T,T,desktop,Trident/7.0
144227,3577509,-5.0,253305.0,0.0,0.0,0.0,-30.0,NaN,NaN,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G930F Build/NRD90M
144228,3577521,-15.0,145955.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,F3111 Build/33.3.A.1.97
144229,3577526,-5.0,172059.0,NaN,NaN,1.0,-5.0,NaN,NaN,NaN,...,chrome 55.0 for android,32.0,855x480,match_status:2,T,F,T,F,mobile,A574BL Build/NMF26F
144230,3577529,-20.0,632381.0,NaN,NaN,-1.0,-36.0,NaN,NaN,NaN,...,chrome 65.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto E (4) Plus Build/NMA26.42-152
144231,3577531,-5.0,55528.0,0.0,0.0,0.0,-7.0,NaN,NaN,0.0,...,chrome 66.0,24.0,2560x1600,match_status:2,T,F,T,F,desktop,MacOS
144232,3577534,-45.0,339406.0,NaN,NaN,-10.0,-100.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,RNE-L03 Build/HUAWEIRNE-L03

In [4]:
train_transaction.tail(50) #preview tain_trasaction.csv

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
35289,3022289,0.0,861221.0,87.950,W,9112.0,250.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35290,3022290,0.0,861240.0,54.500,W,16338.0,555.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35291,3022291,0.0,861243.0,25.000,H,4272.0,111.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35292,3022292,0.0,861250.0,77.000,W,1675.0,174.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35293,3022293,0.0,861267.0,74.158,C,16511.0,179.0,106.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35294,3022294,0.0,861276.0,34.000,W,12501.0,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35295,3022295,0.0,861286.0,115.000,S,15775.0,481.0,150.0,mastercard,102.0,...,1.0,0.0,3535.0,1645.0,0.0,825.0,565.0,0.0,1750.0,120.0
35296,3022296,0.0,861287.0,44.500,W,4153.0,549.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35297,3022297,0.0,861308.0,36.500,W,17482.0,194.0,150.0,mastercard,202.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35298,3022298,0.0,861323.0,24.990,W,16003.0,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35299,3022299,0.0,861338.0,44.500,W,17188.0,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35300,3022300,0.0,861349.0,108.950,W,4090.0,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35301,3022301,0.0,861365.0,49.000,W,7638.0,174.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35302,3022302,0.0,861372.0,50.000,H,9704.0,321.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35303,3022303,0.0,861379.0,49.000,W,4436.0,174.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35304,3022304,0.0,861387.0,93.500,W,2616.0,NaN,150.0,discover,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35305,3022305,0.0,861416.0,317.500,W,17223.0,441.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35306,3022306,0.0,861416.0,300.000,R,16568.0,321.0,150.0,visa,195.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35307,3022307,0.0,861419.0,46.500,W,16326.0,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35308,3022308,0.0,861436.0,58.950,W,12544.0,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35309,3022309,0.0,861444.0,50.000,H,2249.0,343.0,150.0,visa,195.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35310,3022310,0.0,861446.0,12.500,W,4663.0,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35311,3022311,0.0,861454.0,59.000,W,7676.0,512.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35312,3022312,0.0,861471.0,108.500,W,10083.0,555.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35313,3022313,0.0,861490.0,67.950,W,11839.0,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35314,3022314,0.0,861505.0,44.990,W,9500.0,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35315,3022315,0.0,861505.0,29.000,W,16972.0,174.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35316,3022316,0.0,861511.0,50.000,H,10616.0,583.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35317,3022317,0.0,861518.0,88.500,W,10611.0,555.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35318,3022318,0.0,861524.0,59.000,W,14858.0,558.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35319,3022319,0.0,861547.0,100.000,R,6019.0,583.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35320,3022320,0.0,861559.0,100.000,R,7447.0,399.0,150.0,american express,236.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35321,3022321,0.0,861563.0,63.970,W,13324.0,122.0,150.0,mastercard,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35322,3022322,1.0,861569.0,92.990,W,2803.0,100.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35323,3022323,0.0,861576.0,24.500,W,10057.0,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35324,3022324,0.0,861578.0,29.500,W,9500.0,321.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35325,3022325,0.0,861588.0,29.000,W,7728.0,225.0,150.0,mastercard,224.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35326,3022326,0.0,861590.0,153.950,W,17759.0,194.0,150.0,mastercard,202.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35327,3022327,0.0,861597.0,50.000,H,5222.0,111.0,150.0,visa,195.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35328,3022328,0.0,861610.0,75.000,R,6727.0,424.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35329,3022329,0.0,861624.0,49.000,W,7037.0,455.0,150.0,mastercard,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35330,3022330,0.0,861643.0,97.000,W,10349.0,555.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35331,3022331,0.0,861650.0,170.000,H,10486.0,514.0,150.0,mastercard,219.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35332,3022332,0.0,861651.0,75.000,H,12213.0,371.0,150.0,visa,226.0,...,3.0,225.0,225.0,225.0,0.0,0.0,0.0,225.0,225.0,225.0
35333,3022333,0.0,861652.0,141.000,W,10594.0,221.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35334,3022334,0.0,861663.0,57.950,W,15497.0,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35335,3022335,0.0,861665.0,48.950,W,13307.0,428.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35336,3022336,0.0,861693.0,100.000,H,16659.0,170.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35337,3022337,0.0,861702.0,29.500,W,12695.0,490.0,150.0,visa,226.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35338,302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# preview test_transaction data
test_transaction.tail(50)

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
865,3664414,18459642,67.950,W,6530,206.0,150.0,mastercard,126.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
866,3664415,18459643,124.970,W,12544,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
867,3664416,18459647,394.950,W,4121,361.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868,3664417,18459686,59.000,W,9175,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
869,3664418,18459690,82.950,W,8900,385.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
870,3664419,18459704,107.950,W,16115,431.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
871,3664420,18459706,146.000,W,1939,360.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872,3664421,18459709,14.817,C,13832,375.0,185.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
873,3664422,18459809,167.000,W,9537,583.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,3664423,18459826,59.000,W,7919,194.0,150.0,mastercard,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
875,3664424,18459860,59.000,W,6207,355.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,3664425,18459879,47.950,W,12877,194.0,150.0,visa,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
877,3664426,18459922,77.000,W,10023,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
878,3664427,18459938,107.950,W,7508,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
879,3664428,18459941,22.379,C,2796,580.0,106.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
880,3664429,18459943,97.000,W,11815,206.0,150.0,mastercard,126.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,3664430,18459945,59.000,W,16163,551.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
882,3664431,18459945,34.000,W,7452,532.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
883,3664432,18459952,51.000,W,7919,194.0,150.0,mastercard,166.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
884,3664433,18459969,100.000,S,14479,387.0,150.0,visa,226.0,credit,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
885,3664434,18460006,36.950,W,6951,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
886,3664435,18460006,57.950,W,4436,174.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
887,3664436,18460023,159.950,W,18132,567.0,150.0,mastercard,117.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
888,3664437,18460038,55.000,W,9175,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,3664438,18460080,117.000,W,2333,183.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
890,3664439,18460084,226.000,W,8140,453.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
891,3664440,18460095,49.000,W,7508,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
892,3664441,18460099,107.950,W,5241,390.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
893,3664442,18460102,55.000,W,9175,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
894,3664443,18460107,47.950,W,12211,298.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
895,3664444,18460127,59.000,W,9175,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
896,3664445,18460197,2472.110,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
897,3664446,18460240,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
898,3664447,18460269,117.000,W,2755,404.0,150.0,mastercard,102.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
899,3664448,18460286,97.000,W,11815,206.0,150.0,mastercard,126.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
900,3664449,18460292,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
901,3664450,18460311,226.000,W,6952,416.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,3664451,18460391,117.000,W,8002,560.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
903,3664452,18460462,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
904,3664453,18460482,69.950,W,3379,514.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
905,3664454,18460504,664.000,W,9480,170.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
906,3664455,18460515,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
907,3664456,18460539,77.000,W,7508,321.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
908,3664457,18460547,59.000,W,9175,111.0,150.0,visa,226.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
909,3664458,18460552,57.950,W,8695,170.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
910,3664459,18460571,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
911,3664460,18460598,161.000,W,2039,562.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
912,3664461,18460606,311.950,W,12779,100.0,150.0,visa,226.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
913,3664462,18460658,2519.590,W,17675,481.0,150.0,mastercard,219.0,credit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
914,3664463,18460709,25.000,W,15856,390.0,150.0,mastercard,224.0,debit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# preview test_identity.csv
test_identity.tail(50)

,TransactionID,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,...,id-31,id-32,id-33,id-34,id-35,id-36,id-37,id-38,DeviceType,DeviceInfo
141857,4170104,-5.0,275614.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 71.0,NaN,NaN,NaN,F,F,T,F,desktop,NaN
141858,4170107,-5.0,281614.0,0.0,0.0,15.0,-31.0,NaN,NaN,0.0,...,samsung browser 8.2,NaN,NaN,NaN,F,F,T,F,mobile,SAMSUNG SM-G965U Build/R16NW
141859,4170109,-5.0,393270.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 70.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J111M
141860,4170114,0.0,37552.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,google search application 65.0,32.0,2208x1242,match_status:2,T,F,T,T,mobile,iOS Device
141861,4170121,-5.0,228946.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto C
141862,4170123,-5.0,305352.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141863,4170124,-45.0,265807.0,0.0,0.0,-9.0,-12.0,NaN,NaN,0.0,...,chrome 70.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto Z2 Play
141864,4170126,-5.0,376976.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141865,4170129,-5.0,97332.0,NaN,NaN,5.0,-10.0,NaN,NaN,NaN,...,safari 12.0,24.0,3360x2100,match_status:2,T,F,F,F,desktop,MacOS
141866,4170130,-20.0,328188.0,NaN,NaN,-6.0,-29.0,NaN,NaN,NaN,...,mobile safari 12.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
141867,4170131,-20.0,251209.0,NaN,NaN,-9.0,-37.0,NaN,NaN,NaN,...,mobile safari 12.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
141868,4170132,-60.0,630434.0,NaN,NaN,-6.0,-20.0,NaN,NaN,NaN,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,F,F,mobile,DRA-LX3 Build/HUAWEIDRA-LX3
141869,4170136,-5.0,166386.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141870,4170138,-5.0,237382.0,0.0,0.0,4.0,-10.0,NaN,NaN,0.0,...,safari 12.0,24.0,3360x2100,match_status:2,T,F,F,F,desktop,MacOS
141871,4170139,-5.0,115633.0,NaN,NaN,3.0,-7.0,NaN,NaN,NaN,...,mobile safari 12.0,32.0,1136x640,match_status:2,T,F,F,T,mobile,iOS Device
141872,4170142,-5.0,293296.0,0.0,0.0,7.0,-10.0,NaN,NaN,0.0,...,safari 12.0,24.0,3360x2100,match_status:2,T,F,F,F,desktop,MacOS
141873,4170143,-5.0,266356.0,0.0,0.0,0.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141874,4170146,-5.0,131482.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,2208x1242,match_status:2,T,F,F,F,mobile,iOS Device
141875,4170147,-5.0,6258.0,NaN,NaN,2.0,0.0,NaN,NaN,0.0,...,safari 12.0,24.0,2880x1800,match_status:2,T,F,F,T,desktop,MacOS
141876,4170148,-10.0,336091.0,0.0,0.0,1.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141877,4170150,-10.0,389518.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141878,4170151,-35.0,193720.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 12.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
141879,4170152,-5.0,434937.0,0.0,0.0,4.0,-10.0,NaN,NaN,0.0,...,safari 12.0,24.0,3360x2100,match_status:2,T,F,F,F,desktop,MacOS
141880,4170154,-45.0,197823.0,NaN,NaN,15.0,-34.0,38.0,-25.0,NaN,...,samsung browser 8.2,32.0,2220x1081,match_status:2,T,F,T,F,mobile,SAMSUNG SM-G965U Build/R16NW
141881,4170156,-10.0,456446.0,0.0,0.0,4.0,-10.0,NaN,NaN,0.0,...,safari 12.0,24.0,3360x2100,match_status:2,T,F,F,F,desktop,MacOS
141882,4170157,-5.0,1720.0,0.0,0.0,2.0,0.0,NaN,NaN,1.0,...,edge 17.0,24.0,1600x900,match_status:2,T,F,T,T,desktop,Windows
141883,4170170,-45.0,330434.0,NaN,NaN,0.0,-9.0,NaN,NaN,NaN,...,google search application 65.0,NaN,NaN,NaN,F,F,T,F,mobile,NaN
141884,4170172,-45.0,482546.0,NaN,NaN,-5.0,-31.0,NaN,NaN,NaN,...,chrome 70.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-G570M
141885,4170173,-10.0,252507.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141886,4170177,-10.0,325187.0,0.0,0.0,3.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141887,4170180,-10.0,382874.0,0.0,0.0,0.0,-1.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J600G
141888,4170184,-5.0,438252.0,NaN,NaN,3.0,-29.0,NaN,NaN,NaN,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Alpha 950
141889,4170185,-5.0,137631.0,NaN,NaN,16.0,-16.0,NaN,NaN,NaN,...,mobile safari 12.0,32.0,2688x1242,match_status:2,T,F,F,T,mobile,iOS Device
141890,4170187,-5.0,573088.0,NaN,NaN,-3.0,-100.0,NaN,NaN,NaN,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto C Build/NRD90M.070
141891,4170188,-5.0,733003.0,NaN,NaN,-9.0,-11.0,NaN,NaN,NaN,...,samsung browser 8.2,NaN,NaN,NaN,F,F,T,F,mobile,SAMSUNG SM-A730F Build/NMF26X
141892,4170192,-5.0,671043.0,0.0,0.0,-3.0,-100.0,NaN,NaN,0.0,...,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto C Build/NRD90M.070
141893,4170200,-5.0,42211.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,...,ie 11.0 for tablet,24.0,2734x1824,match_status:2,T,F,T,F,desktop,Trident/7.0
141894,4170214,-5.0,449966.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 71.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
141895,4170219,-5.0,139536.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 71.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
141896,4170223,-5.0,532365.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,ANE-LX3
141897,4170224,-35.0,176994.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,mobile safari 12.0,NaN,NaN,NaN,F,F,F,F,mobile,NaN
141898,4170225,-5.0,274407.0,NaN,NaN,0.0,-12.0,NaN,NaN,NaN,...,chrome 71.0,NaN,NaN,NaN,F,F,T,F,desktop,Windows
141899,4170226,-5.0,338012.0,0.0,0.0,-6.0,-10.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,LG-M250
141900,4170228,-10.0,763805.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,Moto G (5) Plus
141901,4170229,-5.0,180957.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 71.0,NaN,NaN,NaN,F,F,T,F,desktop,NaN
141902,4170230,-20.0,473365.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J700M
141903,4170233,-5.0,489917.0,0.0,0.0,-4.0,-32.0,NaN,NaN,0.0,...,chrome 71.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,SM-J320M
141904,4170234,-5.0,110081.0,NaN,NaN,22.0,-31.0,NaN,NaN,NaN,...,mobile safari 10.0,32.0,1334x750,match_status:2,T,F,F,T,mobile,iOS Device
141905,4170236,-45.0,266704.0,NaN,NaN,-3.0,-10.0,NaN,NaN,NaN,...,chrome 43.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,ALE-L23 Build/HuaweiALE-L23
141906,4170239,-10.0,692090.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,samsung browser 8.2,NaN,NaN,NaN,F,F,T,F,mobile,SAMSUNG

In [7]:
print("Columns of the train_identity data set:\n{}".format(train_identity.columns))
print("Columns of the train_transaction data set:\n{}".format(train_transaction.columns))
print("Columns of the test_identity data set:\n{}".format(test_identity.columns))
print("Columns of the test_transaction data set:\n{}".format(test_transaction.columns))

Columns of the train_identity data set:
Index(['TransactionID', 'id_01', 'id_02', 'id_03', 'id_04', 'id_05', 'id_06',
       'id_07', 'id_08', 'id_09', 'id_10', 'id_11', 'id_12', 'id_13', 'id_14',
       'id_15', 'id_16', 'id_17', 'id_18', 'id_19', 'id_20', 'id_21', 'id_22',
       'id_23', 'id_24', 'id_25', 'id_26', 'id_27', 'id_28', 'id_29', 'id_30',
       'id_31', 'id_32', 'id_33', 'id_34', 'id_35', 'id_36', 'id_37', 'id_38',
       'DeviceType', 'DeviceInfo'],
      dtype='object')
Columns of the train_transaction data set:
Index(['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt',
       'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=394)
Columns of the test_identity data set:
Index(['TransactionID', 'id-01', 'id-02', 'id-03', 'id-04', 'id-05', 'id-06',
       'id-07', 'id-08', 'id-09', 'id-10', 'id-11', 'id-12', 'id-13', 'id-14',
       'id-15', 'id-16', 'id-17', 'id-18', 'id-19', 'id-20', 'id-21', 'id-22',
       'id-23', 'id-24', 'id-25', 'id-26', 'id-27', 'id-28', 'id-29', 'id-30',
       'id-31', 'id-32', 'id-33', 'id-34', 'id-35', 'id-36', 'id-37', 'id-38',
       'DeviceType', 'DeviceInfo'],
      dtype='object')
Columns of the test_transaction data set:
Index(['TransactionID', 'TransactionDT', 'TransactionAmt', 'ProductCD',
       'card1', 'card2', 'card3', 'card4', 'card5', 'card6',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=393)

In [8]:
# merge data
train=pd.merge(train_identity, train_transaction, on='TransactionID', how="inner")
test=pd.merge(test_identity, test_transaction, on="TransactionID", how='inner')
test.head()

,TransactionID,id-01,id-02,id-03,id-04,id-05,id-06,id-07,id-08,id-09,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,3663586,-45.0,280290.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3663588,0.0,3579.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,0.0,0.0,310.0,90.0,0.0,310.0,90.0,0.0,0.0,0.0
2,3663597,-5.0,185210.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3663601,-45.0,252944.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3663602,-95.0,328680.0,NaN,NaN,7.0,-33.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Explore train and test data
print("Train data info\n")
train.info()

Train data info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10331 entries, 0 to 10330
Columns: 434 entries, TransactionID to V339
dtypes: float64(402), int64(1), object(31)
memory usage: 34.2+ MB

In [10]:
print("Test data info\n")
test.info()

Test data info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Columns: 433 entries, TransactionID to V339
dtypes: float64(399), int64(3), object(31)
memory usage: 419.6+ KB

In [11]:
# Check for null values
print("Train Null Values")
train.isnull().sum()

Train Null Values

TransactionID       0
id_01               0
id_02             259
id_03            5602
id_04            5602
                 ...
V335             2894
V336             2894
V337             2894
V338             2894
V339             2894
Length: 434, dtype: int64

In [12]:
print("Test Null Values")
test.isnull().sum()

Test Null Values

TransactionID     0
id-01             0
id-02            10
id-03            72
id-04            72
                 ..
V335             56
V336             56
V337             56
V338             56
V339             56
Length: 433, dtype: int64

In [13]:
null_train=train.isnull().sum().sum()
print("total null values\n{}".format(null_train))

total null values
1332343

In [14]:
print("View Null Values to get a better perspective")
null_table=pd.DataFrame(list(train), list(train.isnull().sum()))
null_table.head(50)

View Null Values to get a better perspective

                   0
0      TransactionID
0              id_01
259            id_02
5602           id_03
5602           id_04
540            id_05
540            id_06
9967           id_07
9967           id_08
4768           id_09
4768           id_10
259            id_11
0              id_12
2368           id_13
3077           id_14
259            id_15
837            id_16
345            id_17
7340           id_18
345            id_19
348            id_20
9970           id_21
9966           id_22
9966           id_23
9994           id_24
9967           id_25
9966           id_26
9966           id_27
259            id_28
259            id_29
3235           id_30
275            id_31
3234           id_32
3757           id_33
3268           id_34
259            id_35
259            id_36
259            id_37
259            id_38
259       DeviceType
1417      DeviceInfo
0            isFraud
0      TransactionDT
0     TransactionAmt
0          ProductCD
0              card1
43             card2
1              card3
3              card4
49             card5

In [15]:



# Standardize column names to use underscores
train.columns = [col.replace('-', '_') for col in train.columns]
test.columns = [col.replace('-', '_') for col in test.columns]


# Identify columns with more than 4,000 null values in the train DataFrame
cols_to_drop_train = [col for col in train.columns if train[col].isnull().sum() > 4000]

cols_to_drop=cols_to_drop_train


# Drop the columns that exist in  train and test
train = train.drop(cols_to_drop, axis=1)
test = test.drop(cols_to_drop, axis=1)


# Print remaining columns to verify
print(f"Remaining columns in train: {train.columns}")
print(f"Remaining columns in test: {test.columns}")

Remaining columns in train: Index(['TransactionID', 'id_01', 'id_02', 'id_05', 'id_06', 'id_11', 'id_12',
       'id_13', 'id_14', 'id_15',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=301)
Remaining columns in test: Index(['TransactionID', 'id_01', 'id_02', 'id_05', 'id_06', 'id_11', 'id_12',
       'id_13', 'id_14', 'id_15',
       ...
       'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338',
       'V339'],
      dtype='object', length=300)

In [16]:
print("Information on new table; train")
train.info()

Information on new table; train
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10331 entries, 0 to 10330
Columns: 301 entries, TransactionID to V339
dtypes: float64(280), int64(1), object(20)
memory usage: 23.7+ MB

In [17]:
print("Data Type of data")
train.dtypes

Data Type of data

TransactionID      int64
id_01            float64
id_02            float64
id_05            float64
id_06            float64
                  ...
V335             float64
V336             float64
V337             float64
V338             float64
V339             float64
Length: 301, dtype: object

In [18]:
print("View Null Values to get a better perspective")
null_table=pd.DataFrame(list(train), list(train.isnull().sum()))
train.dtypes

View Null Values to get a better perspective

TransactionID      int64
id_01            float64
id_02            float64
id_05            float64
id_06            float64
                  ...
V335             float64
V336             float64
V337             float64
V338             float64
V339             float64
Length: 301, dtype: object

In [19]:
train.head(50)

,TransactionID,id_01,id_02,id_05,id_06,id_11,id_12,id_13,id_14,id_15,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987004,0.0,70787.0,NaN,NaN,100.000000,NotFound,NaN,-480.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2987008,-5.0,98945.0,0.0,-5.0,100.000000,NotFound,49.0,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2987010,-5.0,191631.0,0.0,0.0,100.000000,NotFound,52.0,NaN,Found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987011,-5.0,221832.0,0.0,-6.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987016,0.0,7460.0,1.0,0.0,100.000000,NotFound,NaN,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2987017,-5.0,61141.0,3.0,0.0,100.000000,NotFound,52.0,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2987022,-15.0,NaN,NaN,NaN,NaN,NotFound,14.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2987038,0.0,31964.0,0.0,-10.0,100.000000,Found,NaN,-300.0,Found,...,0.0,0.0,145.0,25.0,0.0,145.0,25.0,0.0,0.0,0.0
8,2987040,-10.0,116098.0,0.0,0.0,100.000000,NotFound,52.0,NaN,Found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2987048,-5.0,257037.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2987049,-5.0,287959.0,1.0,-11.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2987057,0.0,88525.0,NaN,NaN,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2987066,-5.0,54927.0,0.0,-1.0,100.000000,NotFound,52.0,-360.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2987069,0.0,69542.0,2.0,-4.0,100.000000,Found,NaN,-300.0,Found,...,0.0,0.0,140.0,40.0,0.0,140.0,40.0,0.0,0.0,0.0
14,2987070,0.0,132356.0,1.0,-6.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2987072,0.0,275611.0,0.0,0.0,100.000000,NotFound,20.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2987074,-5.0,419136.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2987084,-5.0,436352.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2987093,-5.0,34810.0,1.0,0.0,93.750000,NotFound,52.0,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2987099,-10.0,129080.0,9.0,-43.0,100.000000,Found,49.0,-300.0,Found,...,0.0,0.0,125.0,0.0,0.0,125.0,0.0,0.0,0.0,0.0
20,2987100,0.0,264818.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2987101,0.0,49557.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2987104,0.0,30696.0,0.0,0.0,100.000000,Found,NaN,-300.0,Found,...,0.0,100.0,100.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2987105,0.0,194580.0,12.0,-6.0,100.000000,NotFound,NaN,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2987108,-15.0,NaN,NaN,NaN,NaN,NotFound,14.0,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2987111,-5.0,252899.0,0.0,0.0,95.080002,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2987114,-5.0,190935.0,6.0,-9.0,100.000000,NotFound,52.0,NaN,Found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2987119,0.0,23923.0,0.0,0.0,100.000000,NotFound,NaN,-480.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2987121,0.0,18305.0,2.0,0.0,100.000000,NotFound,NaN,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2987125,0.0,32876.0,2.0,0.0,100.000000,Found,NaN,-300.0,Found,...,1.0,50.0,50.0,50.0,0.0,0.0,0.0,50.0,50.0,50.0
30,2987130,-10.0,175789.0,0.0,0.0,100.000000,NotFound,52.0,NaN,Found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2987138,-5.0,68343.0,1.0,0.0,100.000000,NotFound,52.0,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2987141,-5.0,110477.0,0.0,-5.0,95.650002,NotFound,49.0,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2987144,-5.0,157470.0,0.0,-5.0,100.000000,Found,49.0,-300.0,Found,...,1.0,200.0,200.0,200.0,0.0,0.0,0.0,200.0,200.0,200.0
34,2987145,-5.0,127488.0,2.0,-11.0,100.000000,NotFound,49.0,-360.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,2987148,-5.0,123916.0,0.0,0.0,100.000000,NotFound,49.0,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,2987156,-5.0,55836.0,0.0,0.0,100.000000,NotFound,52.0,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,2987167,0.0,124221.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,Found,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,2987173,0.0,113499.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,2987183,0.0,79656.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,2987188,-5.0,15464.0,4.0,-44.0,100.000000,Found,55.0,-300.0,Found,...,0.0,0.0,30.0,0.0,0.0,30.0,0.0,0.0,0.0,0.0
41,2987189,-5.0,363527.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2987190,-20.0,157297.0,NaN,NaN,100.000000,NotFound,49.0,NaN,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2987192,-5.0,302597.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2987196,-5.0,211439.0,0.0,0.0,100.000000,NotFound,52.0,NaN,New,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2987197,0.0,77852.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,2987198,0.0,49347.0,0.0,0.0,100.000000,NotFound,NaN,-300.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,2987199,-20.0,146516.0,0.0,0.0,100.000000,NotFound,49.0,NaN,Unknown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2987207,-5.0,84798.0,4.0,0.0,100.000000,NotFound,49.0,-480.0,New,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,2987209,-5.0,86577.0,6.0,0.0,100.000000,NotFound,52.0,NaN,Found,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
print("Description of train\n{}".format(dict(train.describe())))

Description of train
{'TransactionID': count    1.033100e+04
mean     3.006749e+06
std      9.931412e+03
min      2.987004e+06
25%      2.998435e+06
50%      3.007876e+06
75%      3.015252e+06
max      3.022336e+06
Name: TransactionID, dtype: float64, 'id_01': count    10331.000000
mean        -7.979576
std         13.550425
min       -100.000000
25%         -5.000000
50%         -5.000000
75%          0.000000
max          0.000000
Name: id_01, dtype: float64, 'id_02': count     10072.000000
mean     134793.752383
std      125141.534505
min        1120.000000
25%       51738.500000
50%       98590.000000
75%      175037.000000
max      998295.000000
Name: id_02, dtype: float64, 'id_05': count    9791.000000
mean        1.860382
std         5.206876
min       -30.000000
25%         0.000000
50%         0.000000
75%         1.000000
max        52.000000
Name: id_05, dtype: float64, 'id_06': count    9791.000000
mean       -5.931570
std        16.192156
min      -100.000000
25%        -4.000000
50%         0.000000
75%         0.000000
max         0.000000
Name: id_06, dtype: float64, 'id_11': count    10072.000000
mean        99.654554
std          1.284654
min         90.000000
25%        100.000000
50%        100.000000
75%        100.000000
max        100.000000
Name: id_11, dtype: float64, 'id_13': count    7963.000000
mean       47.418435
std        10.699932
min        11.000000
25%        49.000000
50%        52.000000
75%        52.000000
max        63.000000
Name: id_13, dtype: float64, 'id_14': count    7254.000000
mean     -344.143921
std        86.459086
min      -600.000000
25%      -360.000000
50%      -300.000000
75%      -300.000000
max       600.000000
Name: id_14, dtype: float64, 'id_17': count    9986.000000
mean      180.565892
std        26.984617
min       100.000000
25%       166.000000
50%       166.000000
75%       225.000000
max       225.000000
Name: id_17, dtype: float64, 'id_19': count    9986.000000
mean      363.065592
std       146.591067
min       100.000000
25%       266.000000
50%       352.000000
75%       492.000000
max       670.000000
Name: id_19, dtype: float64, 'id_20': count    9983.000000
mean      390.697886
std       153.018229
min       100.000000
25%       222.000000
50%       401.000000
75%       533.000000
max       638.000000
Name: id_20, dtype: float64, 'id_32': count    7097.000000
mean       26.518247
std         3.742295
min        16.000000
25%        24.000000
50%        24.000000
75%        32.000000
max        32.000000
Name: id_32, dtype: float64, 'isFraud': count    10331.000000
mean         0.048204
std          0.214208
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: isFraud, dtype: float64, 'TransactionDT': count     10331.000000
mean     520594.117607
std      224209.567417
min       86506.000000
25%      337140.000000
50%      531622.000000
75%      703832.000000
max      861693.000000
Name: TransactionDT, dtype: float64, 'TransactionAmt': count    10331.000000
mean        84.331071
std         98.016355
min          0.292000
25%         29.243000
50%         50.000000
75%        100.000000
max       1000.000000
Name: TransactionAmt, dtype: float64, 'card1': count    10331.000000
mean      9810.634595
std       5061.850824
min       1004.000000
25%       5742.500000
50%       9803.000000
75%      14649.500000
max      18375.000000
Name: card1, dtype: float64, 'card2': count    10288.000000
mean       390.319984
std        160.713847
min        100.000000
25%        264.000000
50%        408.000000
75%        545.000000
max        598.000000
Name: card2, dtype: float64, 'card3': count    10330.000000
mean       157.856922
std         16.522951
min        100.000000
25%        150.000000
50%        150.000000
75%        150.000000
max        225.000000
Name: card3, dtype: float64, 'card5': count    10282.000000
mean       196.013908
std         43.340529
min        100.000000
25%        162.000000
50%        224.000000
75%        226.000000
max        237.000000
Name: card5, dtype: float64, 'addr1': count    8704.000000
mean      297.215303
std       109.748181
min       100.000000
25%       204.000000
50%       299.000000
75%       337.000000
max       540.000000
Name: addr1, dtype: float64, 'addr2': count    8704.000000
mean       82.798254
std        11.125400
min        13.000000
25%        87.000000
50%        87.000000
75%        87.000000
max       102.000000
Name: addr2, dtype: float64, 'C1': count    10331.000000
mean        12.969896
std         77.358592
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        800.000000
Name: C1, dtype: float64, 'C2': count    10331.000000
mean        21.952086
std        126.557497
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max       1197.000000
Name: C2, dtype: float64, 'C3': count    10331.000000
mean         0.052947
std          0.295503
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         16.000000
Name: C3, dtype: float64, 'C4': count    10331.000000
mean         7.118672
std         45.320684
min          0.000000
25%          0.000000
50%          1.000000
75%          1.000000
max        559.000000
Name: C4, dtype: float64, 'C5': count    10331.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: C5, dtype: float64, 'C6': count    10331.000000
mean         7.308876
std         45.809832
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        569.000000
Name: C6, dtype: float64, 'C7': count    10331.000000
mean         4.707773
std         32.369908
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max        399.000000
Name: C7, dtype: float64, 'C8': count    10331.000000
mean         8.678540
std         49.252071
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        551.000000
Name: C8, dtype: float64, 'C9': count    10331.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: C9, dtype: float64, 'C10': count    10331.000000
mean        10.682606
std         61.283025
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        700.000000
Name: C10, dtype: float64, 'C11': count    10331.000000
mean        10.085277
std         59.387154
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        598.000000
Name: C11, dtype: float64, 'C12': count    10331.000000
mean         7.201626
std         48.749738
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max        567.000000
Name: C12, dtype: float64, 'C13': count    10331.000000
mean        11.915884
std         62.406858
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        601.000000
Name: C13, dtype: float64, 'C14': count    10331.000000
mean         4.852386
std         29.185752
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        382.000000
Name: C14, dtype: float64, 'D1': count    10331.000000
mean        22.003485
std         83.367732
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        635.000000
Name: D1, dtype: float64, 'V95': count    10331.000000
mean         0.225922
std          0.801541
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         14.000000
Name: V95, dtype: float64, 'V96': count    10331.000000
mean         0.452715
std          2.342371
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         40.000000
Name: V96, dtype: float64, 'V97': count    10331.000000
mean         0.295615
std          1.124883
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         22.000000
Name: V97, dtype: float64, 'V98': count    10331.000000
mean         0.033298
std          0.218803
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          5.000000
Name: V98, dtype: float64, 'V99': count    10331.000000
mean         0.212177
std          1.767703
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         34.000000
Name: V99, dtype: float64, 'V100': count    10331.000000
mean         0.091375
std          0.670044
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         11.000000
Name: V100, dtype: float64, 'V101': count    10331.000000
mean         0.105895
std          0.558673
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         12.000000
Name: V101, dtype: float64, 'V102': count    10331.00000
mean         0.11693
std          0.59935
min          0.00000
25%          0.00000
50%          0.00000
75%          0.00000
max         12.00000
Name: V102, dtype: float64, 'V103': count    10331.000000
mean         0.113639
std          0.591042
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         12.000000
Name: V103, dtype: float64, 'V104': count    10331.000000
mean         0.079566
std          0.401666
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          7.000000
Name: V104, dtype: float64, 'V105': count    10331.000000
mean         0.116252
std          0.714758
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max         13.000000
Name: V105, dtype: float64, 'V106': count    10331.000000
mean         0.083341
std          0.409382
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          7.000000
Name: V106, dtype: float64, 'V107': count    10331.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
Name: V107, dtype: float64, 'V108': count    10331.000000
mean         1.009873
std          0.114316
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V108, dtype: float64, 'V109': count    10331.000000
mean         1.010164
std          0.115554
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V109, dtype: float64, 'V110': count    10331.000000
mean         1.010164
std          0.115554
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V110, dtype: float64, 'V111': count    10331.000000
mean         1.010841
std          0.126302
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V111, dtype: float64, 'V112': count    10331.000000
mean         1.011035
std          0.127809
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V112, dtype: float64, 'V113': count    10331.000000
mean         1.011035
std          0.127809
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          4.000000
Name: V113, dtype: float64, 'V114': count    10331.000000
mean         1.013164
std          0.134261
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: V114, dtype: float64, 'V115': count    10331.000000
mean         1.014229
std          0.138764
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: V115, dtype: float64, 'V116': count    10331.000000
mean         1.013939
std          0.137743
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          5.000000
Name: V116, dtype: float64, 'V117': count    10331.000000
mean         1.005711
std          0.076632
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V117, dtype: float64, 'V118': count    10331.000000
mean         1.005808
std          0.077254
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V118, dtype: float64, 'V119': count    10331.000000
mean         1.005808
std          0.077254
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V119, dtype: float64, 'V120': count    10331.000000
mean         1.005905
std          0.079104
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V120, dtype: float64, 'V121': count    10331.000000
mean         1.006001
std          0.079707
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V121, dtype: float64, 'V122': count    10331.000000
mean         1.006001
std          0.079707
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: V122, dtype: float64, 'V123': count    10331.000000
mean         1.048301
std          0.310029
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          9.000000
Name: V123, dtype: float64, 'V124': count    10331.000000
mean         1.059626
std          0.337015
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          9.000000
Name: V124, dtype: float64, 'V125': count    10331.000000
mean         1.052367
std          0.320133
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          9.000000
Name: V125, dtype: float64, 'V126': count    10331.000000
mean        29.667528
std        516.956780
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V126, dtype: float64, 'V127': count    10331.000000
mean        42.941687
std        540.274128
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V127, dtype: float64, 'V128': count    10331.000000
mean        33.407470
std        519.652023
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V128, dtype: float64, 'V129': count    10331.000000
mean         3.100059
std         36.523511
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1000.000000
Name: V129, dtype: float64, 'V130': count    10331.000000
mean        11.309192
std         95.165290
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       2700.000000
Name: V130, dtype: float64, 'V131': count    10331.000000
mean         5.730061
std         49.861437
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       1300.000000
Name: V131, dtype: float64, 'V132': count    10331.000000
mean        10.978829
std         87.886521
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       3000.000000
Name: V132, dtype: float64, 'V133': count    10331.000000
mean        11.813217
std         90.137555
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       3000.000000
Name: V133, dtype: float64, 'V134': count    10331.000000
mean        11.522829
std         89.142398
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max       3000.000000
Name: V134, dtype: float64, 'V135': count    10331.000000
mean        15.050094
std        505.180870
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V135, dtype: float64, 'V136': count    10331.000000
mean        19.270085
std        510.652885
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V136, dtype: float64, 'V137': count    10331.000000
mean        15.615066
std        505.558785
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      50820.000000
Name: V137, dtype: float64, 'V138': count    7399.000000
mean        0.021489
std         0.270067
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         8.000000
Name: V138, dtype: float64, 'V139': count    7399.000000
mean        0.669820
std         1.122671
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max        18.000000
Name: V139, dtype: float64, 'V140': count    7399.000000
mean        0.691985
std         1.171496
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max        18.000000
Name: V140, dtype: float64, 'V141': count    7399.000000
mean        0.028923
std         0.214319
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         5.000000
Name: V141, dtype: float64, 'V142': count    7399.000000
mean        0.036356
std         0.282695
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         6.000000
Name: V142, dtype: float64, 'V143': count    7399.000000
mean        9.140019
std        11.163516
min         0.000000
25%         0.000000
50%         0.000000
75%        18.000000
max        40.000000
Name: V143, dtype: float64, 'V144': count    7399.000000
mean       10.619678
std        12.889699
min         0.000000
25%         0.000000
50%         0.000000
75%        22.000000
max        51.000000
Name: V144, dtype: float64, 'V145': count    7399.000000
mean       63.222327
std        70.787802
min         0.000000
25%         0.000000
50%         1.000000
75%       140.000000
max       187.000000
Name: V145, dtype: float64, 'V146': count    7399.00000
mean        0.07947
std         0.44077
min         0.00000
25%         0.00000
50%         0.00000
75%         0.00000
max         7.00000
Name: V146, dtype: float64, 'V147': count    7399.000000
mean        0.080822
std         0.447828
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         8.000000
Name: V147, dtype: float64, 'V148': count    7399.000000
mean        0.488985
std         0.538445
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: V148, dtype: float64, 'V149': count    7399.000000
mean        0.491147
std         0.542985
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: V149, dtype: float64, 'V150': count    7399.000000
mean      962.433707
std      1088.246631
min         1.000000
25%         1.000000
50%         1.000000
75%      1998.000000
max      2755.000000
Name: V150, dtype: float64, 'V151': count    7399.000000
mean       23.779430
std        25.426303
min         1.000000
25%         1.000000
50%         1.000000
75%        52.000000
max        57.000000
Name: V151, dtype: float64, 'V152': count    7399.000000
mean       29.509663
std        31.735936
min         1.000000
25%         1.000000
50%         1.000000
75%        65.000000
max        67.000000
Name: V152, dtype: float64, 'V153': count    7399.000000
mean        0.487498
std         0.534128
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: V153, dtype: float64, 'V154': count    7399.000000
mean        0.489255
std         0.544690
min         0.000000
25%         0.000000

In [21]:
from sklearn.impute import SimpleImputer

mean_columns = ["id_02", "id_06", "id_11", "id_13", 'id_19', 'id_20', 'card3', 'card5']
median_columns = ["id_32", 'addr2', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149']
mode_columns = [
    "id_05", "id_14", "id_17", 'card2', "V152", 'V161', 'V158', 'V162', 'V163', 'V165', 'V167', 'V168', 'V170', 'V171', 'V172', 
    'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 
    'V188', 'V189', 'V190', 'V191', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203','V204','V205', 
    'V206', 'V207', 'V208', 'V209', 'V210','V211','V212','V213','V214','V215','V216','V217','V218','V219','V220','V221','V222',
    'V223','V224','V225','V226','V227','V228','V229','V230','V231','V232','V233','V234','V235','V236','V237','V238','V239','V240',
    'V241','V242','V243','V244','V245','V246','V247','V248','V249','V250','V251','V252','V253','V254','V255','V256','V257','V258',
    'V259','V260','V261','V262','V263','V264','V265','V266','V267','V268','V269','V270','V271', 'V272','V273','V274','V275','V276',
    'V277','V278','V279','V280','V281','V282','V283','V284','V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291','V292','V293',
    'V294', 'V295','V296','V297','V298','V299','V300','V301','V302','V303','V304','V305','V306','V307','V308','V309','V310','V311',
    'V312','V313','V314','V315','V316','V317','V318','V319','V320','V321','V322','V323','V324','V325','V326','V327','V328','V329',
    'V330','V331','V332','V333','V334','V335', 'V336', 'V337', 'V338', 'V339', 'addr1'
]


# Imputers
imp_mean = SimpleImputer(strategy='mean')
imp_median = SimpleImputer(strategy='median')
imp_mode = SimpleImputer(strategy='most_frequent')

# Impute the columns
train[mean_columns] = imp_mean.fit_transform(train[mean_columns])
train[median_columns] = imp_median.fit_transform(train[median_columns])
train[mode_columns] = imp_mode.fit_transform(train[mode_columns])
test[mean_columns] = imp_mean.fit_transform(test[mean_columns])
test[median_columns] = imp_median.fit_transform(test[median_columns])
test[mode_columns] = imp_mode.fit_transform(test[mode_columns])



# fill the rest column with the standard deviation
# List of columns to fill with standard deviation

std_columns = ['V150', 'V151', 'V153', 'V154', 'V155', 'V156', 'V157', 'V159', 'V160', 'V164', 'V166', 'V169', 'V192', 'V193']


# Calculate standard deviations for the columns
std_values = train[std_columns].std().to_dict()

# Function to fill missing values with standard deviation
def fill_with_std(df, columns, std_values):
    for col in columns:
        df[col].fillna(std_values[col], inplace=True)
    return df

# Fill missing values in the train DataFrame
train = fill_with_std(train, std_columns, std_values)

# Fill missing values in the test DataFrame using the same standard deviation values
test = fill_with_std(test, std_columns, std_values)

In [22]:
columns_with_nulls = [
    "id_15", "id_16", "id_28", "id_29", "id_30", "id_31", "id_33", "id_34", "id_35", 
    "id_36", "id_37", "id_38", "DeviceType", "DeviceInfo", "card4", "card6", 
    "P_emaildomain", "R_emaildomain"
]

train[columns_with_nulls].dtypes #data type of null values

id_15            object
id_16            object
id_28            object
id_29            object
id_30            object
id_31            object
id_33            object
id_34            object
id_35            object
id_36            object
id_37            object
id_38            object
DeviceType       object
DeviceInfo       object
card4            object
card6            object
P_emaildomain    object
R_emaildomain    object
dtype: object

In [23]:
print("List of Columns")
list(train.columns)

List of Columns

['TransactionID',
 'id_01',
 'id_02',
 'id_05',
 'id_06',
 'id_11',
 'id_12',
 'id_13',
 'id_14',
 'id_15',
 'id_16',
 'id_17',
 'id_19',
 'id_20',
 'id_28',
 'id_29',
 'id_30',
 'id_31',
 'id_32',
 'id_33',
 'id_34',
 'id_35',
 'id_36',
 'id_37',
 'id_38',
 'DeviceType',
 'DeviceInfo',
 'isFraud',
 'TransactionDT',
 'TransactionAmt',
 'ProductCD',
 'card1',
 'card2',
 'card3',
 'card4',
 'card5',
 'card6',
 'addr1',
 'addr2',
 'P_emaildomain',
 'R_emaildomain',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'C11',
 'C12',
 'C13',
 'C14',
 'D1',
 'V95',
 'V96',
 'V97',
 'V98',
 'V99',
 'V100',
 'V101',
 'V102',
 'V103',
 'V104',
 'V105',
 'V106',
 'V107',
 'V108',
 'V109',
 'V110',
 'V111',
 'V112',
 'V113',
 'V114',
 'V115',
 'V116',
 'V117',
 'V118',
 'V119',
 'V120',
 'V121',
 'V122',
 'V123',
 'V124',
 'V125',
 'V126',
 'V127',
 'V128',
 'V129',
 'V130',
 'V131',
 'V132',
 'V133',
 'V134',
 'V135',
 'V136',
 'V137',
 'V138',
 'V139',
 'V140',
 'V141',
 'V142',
 'V143',
 'V144',
 'V145',
 'V146',
 'V147',
 'V148',
 'V149',
 'V150',
 'V151',
 'V152',
 'V153',
 'V154',
 'V155',
 'V156',
 'V157',
 'V158',
 'V159',
 'V160',
 'V161',
 'V162',
 'V163',
 'V164',
 'V165',
 'V166',
 'V167',
 'V168',
 'V169',
 'V170',
 'V171',
 'V172',
 'V173',
 'V174',
 'V175',
 'V176',
 'V177',
 'V178',
 'V179',
 'V180',
 'V181',
 'V182',
 'V183',
 'V184',
 'V185',
 'V186',
 'V187',
 'V188',
 'V189',
 'V190',
 'V191',
 'V192',
 'V193',
 'V194',
 'V195',
 'V196',
 'V197',
 'V198',
 'V199',
 'V200',
 'V201',
 'V202',
 'V203',
 'V204',
 'V205',
 'V206',
 'V207',
 'V208',
 'V209',
 'V210',
 'V211',
 'V212',
 'V213',
 'V214',
 'V215',
 'V216',
 'V217',
 'V218',
 'V219',
 'V220',
 'V221',
 'V222',
 'V223',
 'V224',
 'V225',
 'V226',
 'V227',
 'V228',
 'V229',
 'V230',
 'V231',
 'V232',
 'V233',
 'V234',
 'V235',
 'V236',
 'V237',
 'V238',
 'V239',
 'V240',
 'V241',
 'V242',
 'V243',
 'V244',
 'V245',
 'V246',
 'V247',
 'V248',
 'V249',
 'V250',
 'V251',
 'V252',
 'V253',
 'V254',
 'V255',
 'V256',
 'V257',
 'V258',
 'V259',
 'V260',
 'V261',
 'V262',
 'V263',
 'V264',
 'V265',
 'V266',
 'V267',
 'V268',
 'V269',
 'V270',
 'V271',
 'V272',
 'V273',
 'V274',
 'V275',
 'V276',
 'V277',
 'V278',
 'V279',
 'V280',
 'V281',
 'V282',
 'V283',
 'V284',
 'V285',
 'V286',
 'V287',
 'V288',
 'V289',
 'V290',
 'V291',
 'V292',
 'V293',
 'V294',
 'V295',
 'V296',
 'V297',
 'V298',
 'V299',
 'V300',
 'V301',
 'V302',
 'V303',
 'V304',
 'V305',
 'V306',
 'V307',
 'V308',
 'V309',
 'V310',
 'V311',
 'V312',
 'V313',
 'V314',
 'V315',
 'V316',
 'V317',
 'V318',
 'V319',
 'V320',
 'V321',
 'V322',
 'V323',
 'V324',
 'V325',
 'V326',
 'V327',
 'V328',
 'V329',
 'V330',
 'V331',
 'V332',
 'V333',
 'V334',
 'V335',
 'V336',
 'V337',
 'V338',
 'V339']

In [24]:
# Apply LabelEncoder to each column with nulls
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for column in columns_with_nulls:
    train[column] = encoder.fit_transform(train[column])
    test[column]=encoder.fit_transform(test[column])

In [25]:
# Assuming columns_with_nulls contains the list of columns with null values

# Drop columns with nulls from train and test datasets
train_null = train.drop(columns_with_nulls, axis=1)
test_null = test.drop(columns_with_nulls, axis=1)

# Apply KNN imputer
from sklearn.impute import KNNImputer

# Initialize KNNImputer
kn = KNNImputer(n_neighbors=5)

# Fit and transform on train data
train_imputed = kn.fit_transform(train[columns_with_nulls])

# Transform test data (using the imputer learned from train data)
test_imputed = kn.transform(test[columns_with_nulls])

# Convert imputed arrays back to DataFrame
train_imputed_pd = pd.DataFrame(train_imputed, columns=columns_with_nulls)
test_imputed_pd = pd.DataFrame(test_imputed, columns=columns_with_nulls)

# Concatenate imputed data with non-null columns
train_final = pd.concat([train_null, train_imputed_pd], axis=1)
test_final = pd.concat([test_null, test_imputed_pd], axis=1)

In [26]:
# check for null values 
print("train  null value in table:\n{}".format(train_final.isnull().sum().sum()))
print("test  null value in table:\n{}".format(test_final.isnull().sum().sum()))

train  null value in table:
0
test  null value in table:
8

In [27]:
# lets chekc which null value is in table:
for col in test_final.columns:
    if test_final[col].isnull().any():
        print(col, "column contains null values")

D1 column contains null values

In [28]:
# describing D1
test_final['D1'].describe()

count    116.000000
mean      72.844828
std      143.946705
min        0.000000
25%        0.000000
50%        0.000000
75%       98.000000
max      564.000000
Name: D1, dtype: float64

In [29]:
# fill D1 na with median
# calculate median
D1_mid=test_final['D1'].median()
test_final['D1'].fillna(D1_mid, inplace=True)

In [30]:
#check for na
test_final.isnull().sum().sum()

0

In [31]:
# Check for object type columns in train_final
object_columns = [col for col in train_final.columns if train_final[col].dtypes == 'object']

# Print each column name and its data type
for col in object_columns:
    print(f"Column '{col}' is of type 'object'.")

Column 'id_12' is of type 'object'.
Column 'ProductCD' is of type 'object'.

In [32]:
columns=['id_12', 'ProductCD']
for column in columns:
    train_final[column] = encoder.fit_transform(train_final[column])
    test_final[column]=encoder.fit_transform(test_final[column])

In [33]:
# Get data ready for machine learning

colums_to_drop=["TransactionID", "isFraud", "TransactionDT" ]
X=train_final.drop(colums_to_drop,  axis=1)
y=train_final["isFraud"]# Import necessary libraries

In [34]:
from sklearn.model_selection import TimeSeriesSplit
# Initialize the TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits=5)

# Iterate through the splits
for train_index, test_index in tscv.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Print or check the shapes of the splits
    print("X_train shape:", X_train.shape, "X_test shape:", X_test.shape)
    print("y_train shape:", y_train.shape, "y_test shape:", y_test.shape)

X_train shape: (1726, 298) X_test shape: (1721, 298)
y_train shape: (1726,) y_test shape: (1721,)
X_train shape: (3447, 298) X_test shape: (1721, 298)
y_train shape: (3447,) y_test shape: (1721,)
X_train shape: (5168, 298) X_test shape: (1721, 298)
y_train shape: (5168,) y_test shape: (1721,)
X_train shape: (6889, 298) X_test shape: (1721, 298)
y_train shape: (6889,) y_test shape: (1721,)
X_train shape: (8610, 298) X_test shape: (1721, 298)
y_train shape: (8610,) y_test shape: (1721,)

In [35]:
from sklearn.ensemble import RandomForestClassifier
Gr_model=RandomForestClassifier
model=Gr_model(n_estimators=100,random_state=0)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [36]:
# drop transaction id in test_final
drop=["TransactionID", "TransactionDT"]
test_predict=test_final.drop(drop, axis=1)
predictions=model.predict(test_predict)

In [37]:
y_preds=model.predict(X_train)

In [38]:
from sklearn.metrics import accuracy_score
# Make predictions on the test set
y_preds = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = model.score(X_test, y_test)

print("Model Accuracy:", accuracy)

Model Accuracy: 0.9587449157466589

In [39]:
model.score(X_test, y_test)

0.9587449157466589

In [40]:
# how to submit data 
sample=pd.read_csv("sample_submission.csv")
sample

        TransactionID  isFraud
0             3663549      0.5
1             3663550      0.5
2             3663551      0.5
3             3663552      0.5
4             3663553      0.5
...               ...      ...
506686        4170235      0.5
506687        4170236      0.5
506688        4170237      0.5
506689        4170238      0.5
506690        4170239      0.5

[506691 rows x 2 columns]

In [41]:
predictions=list(predictions)

In [42]:

table = pd.DataFrame({"TransactionID": test["TransactionID"], "isFraud": predictions})

In [43]:
table.head(20)

    TransactionID  isFraud
0         3663586      0.0
1         3663588      0.0
2         3663597      0.0
3         3663601      0.0
4         3663602      0.0
5         3663622      0.0
6         3663624      0.0
7         3663626      0.0
8         3663629      0.0
9         3663658      0.0
10        3663669      0.0
11        3663677      0.0
12        3663693      0.0
13        3663702      0.0
14        3663704      0.0
15        3663708      0.0
16        3663710      0.0
17        3663714      0.0
18        3663715      0.0
19        3663716      0.0

In [44]:
table.to_csv("kaggledatasets.csv", index=False) # export predictions